### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [wuxialearn/wuxialearn#12]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8729242325

Could you please take a look? Thanks!

**Comment by wuxialearn** [comment]
@linsui Thanks for notifying me. The issue was the usage of `WidgetStateProperty` which the flutter version I was using (3.19.6) did not support. I changed the flutter version in https://github.com/wuxialearn/wuxialearn/commit/0852c460b5581f0340d29f6d1ca8866738972bbe, which should fix the issue. I guess I will need a new tag?

**Comment by linsui** [comment]
Thanks!
